version: 0.0
os: linux

files:
  - source: files
    destination: /var/www/html

permissions:
  - object: /var/www/html
    mode: 777
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/stop-server.sh
  AfterInstall:
    - location: scripts/start-server.sh
